# Generated by Django 5.0.3 on 2024-05-08 12:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Catagory',
            fields=[
                ('cid', models.AutoField(primary_key=True, serialize=False)),
                ('cname', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('pid', models.AutoField(primary_key=True, serialize=False)),
                ('pname', models.CharField(max_length=25)),
                ('pprice', models.IntegerField()),
                ('disc', models.TextField()),
                ('pimage', models.ImageField(upload_to='')),
                ('c_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.catagory')),
            ],
        ),
    ]
