# Generated by Django 5.0.3 on 2024-05-16 11:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_alter_product_pimage'),
    ]

    operations = [
        migrations.CreateModel(
            name='Top_Product',
            fields=[
                ('tid', models.AutoField(primary_key=True, serialize=False)),
                ('t_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.product')),
            ],
        ),
    ]
