# Generated by Django 5.0.3 on 2024-05-21 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_delete_wishlist'),
    ]

    operations = [
        migrations.CreateModel(
            name='Just',
            fields=[
                ('js', models.AutoField(primary_key=True, serialize=False)),
            ],
        ),
    ]
