# Generated by Django 5.0.3 on 2024-05-22 05:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0007_just'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Just',
        ),
    ]
